name: Feature request
description: Suggest an idea
labels: ["enhancement"]

body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: Describe your idea as detailed as possible.
    validations:
      required: true
